### ISSUE TITLE
Question on dimensions of Datasets

### ISSUE THREAD

**Issue by jjwow2** [QData/spacetimeformer#11]
Hello -

I am looking to try new datasets with your model, but just having a little hard time understanding the x_dim and y_dim hard coded into the train.py. 

What exactly do each of these mean? 

For example, for the solar_energy data set, I see that the y_dim is 137 because it has 137 features, but where does the 6 come from?

**Comment by abcde-1447** [comment]
@jjwow2 My understanding is time embedding has 6 dimensions, see this class: https://github.com/QData/spacetimeformer/blob/90721a11906874027b3ac658a27fbbfde3150e9d/spacetimeformer/data/csv_dataset.py#L16-L16

**Comment by jakegrigsby** [comment]
Yeah the 6 is pretty arbitrary, it comes from dividing calendar dates into (Year, Month, Day, Hour, Minute, Second).

**Comment by jjwow2** [comment]
Thank you! I was able to implement my own dataset successfully with this information but might be removing the seconds embedding in the future. 

Overall the results are pretty good (.09 RMSE), but sometimes the pytorch lightning test method returns some non-sensical results, which I need to figure out.
