### ISSUE TITLE
0 value features causing issues with reverse scaling

### ISSUE THREAD

**Issue by jjwow2** [QData/spacetimeformer#12]
Hello - 

I was getting some nonsense loss function results in my final prediction (ex: MSE >100000 for 0-1 scaled features) and I believe I figured out the source of the issue. 

I believe the reverse scaling function was having an issue with my "precipitation" features, which are normally 0. I am working on my own fix but just wanted to pass along.

**Comment by jakegrigsby** [comment]
That's strange, let me know if you find anything. I guess the standard normalization scheme might have stability issues if std dev is very low? We've tested on a dataset  that also involves precipitation and has lots of 0s with poor results. Maybe related to this issue...
