### ISSUE TITLE
Training times.

### ISSUE THREAD

**Issue by InterHato** [QData/spacetimeformer#14]
For the example commands stated in the repository what are the training times that we should be expecting. And what were the hardware specification these tests were run on, with 4 gpu's specified keeping in mind.

**Comment by jakegrigsby** [comment]
Sorry for the late reply, I missed this one. 

Our lab servers have a mix of different GPUs, but I looked through some of the Metr-LA log files and it looks like on 4 NVIDIA GeForce GTX 1080 Ti (11 GB) a training run takes a little over three hours.
