### ISSUE TITLE
Unable to import spacetimeformer from spacetimeformer

### ISSUE THREAD

**Issue by daniela-winkler** [QData/spacetimeformer#18]
Hello, I'm unable to import spacetimeformer from spacetimeformer. However, I can import spacetimeformer_model. My goal is to run the demo notebook and to run kernel= spacetimeformer(g=3, m=2). Could you help me solving this issue? Thanks!

**Comment by jakegrigsby** [comment]
I apologize for the confusion, but the code you are referencing is boilerplate generated by the documentation website we are trying to set up. Unfortunately I have been distracted by some other deadlines and I have not finished creating the documentation. This will be completed over the next few weeks when I am able to refocus on this project. For a starting example, please install the repo with `git clone ...`, then `pip install -e .`. We have some starting training commands on the README. We do not currently have a notebook tutorial setup, but this is something requested by other issues (#6) and I plan on adding them to the next version.
