### ISSUE TITLE
How many epochs?

### ISSUE THREAD

**Issue by Suppersine** [QData/spacetimeformer#22]
I am renting an expensive cloud service ($15/hr), and I just want to know how many epochs is this setting? So that I can calculate/estimate the running time.
```
python train.py spacetimeformer metr-la --start_token_len 3 --batch_size 32 \
--gpus 0 1 2 3 --grad_clip_norm 1 --d_model 128 --d_ff 512 --enc_layers 5 \
--dec_layers 4 --dropout_emb .3 --dropout_ff .3 --dropout_qkv 0 \ 
--run_name spatiotemporal_metr-la --base_lr 1e-3 --l2_coeff 1e-2 \
```

**Comment by jakegrigsby** [comment]
Looking at my log files with 4 gpus it should be ~3.5 hours and ~20 epochs. 

(sorry for the delay on this, I'm catching up on issues)
