### ISSUE TITLE
Where you given the location information of NY - TX in the asos model, like lat long

### ISSUE THREAD

**Issue by jeevanu** [QData/spacetimeformer#25]
Where you given the location information of NY - TX in the asos model, like lat long

**Comment by jakegrigsby** [comment]
No, the location information (like lat/long or distance between the stations) isn't given to the model. The model learns the relationships between each variable during training using "variable embeddings" that are randomly initialized. Those embeddings let the attention mechanism distinguish between each variable and learn patterns between them. In the NY-TX case it usually learns the location relationship automatically, and we try to show an example of that in Figure 4 of the paper.

**Comment by jeevanu** [comment]
Thanks
