### ISSUE TITLE
Feature Request: Possible to Retrieve Raw Prediction Results?

### ISSUE THREAD

**Issue by JCLGeorgia** [QData/spacetimeformer#33]
Hello - 

I hope all is well. Is it possible to produce raw predicted values from the model? I see the options to generate prediction plots with wandb, but is there any possibility of producing the raw data for each feature in a dataset.

The goal I have is that there is research that does not normalize their input data, so I would like to inverse transform to produce non-normalized distance metrics of the predicted results. Inputting non-normalized values to the model I believe would cause issues. 

Any thoughts you have would be appreciated and thank you for the wonderful source code + information. 

Best!

**Comment by jakegrigsby** [comment]
There are some pytorch_lightning based ways to do this but honestly I think the least confusing way is to use the trained model as a regular pytorch module. I added a `predict` function to `Forecaster` that handles making the unknown `y_t` (target sequence variable values) and dealing with the distributional output of spacetimeformer. It takes a batch of `x_c, y_c, x_t` tensors (on the GPU) and returns a un-normalized numpy array (CPU) of the predictions.
