### ISSUE TITLE
Question: Can we use Spacetimeformer for Recommendation?

### ISSUE THREAD

**Issue by swami-venkatesan** [QData/spacetimeformer#36]
Hi,
   I read your paper last year and was really impressed on the model and its results. Thanks for your contribution. I am working on recommendation engine models and I was wondering if we could use this model architecture for sequential recommendations (especially short session where we have no previous user history or user information)?

**Comment by jakegrigsby** [comment]
Thanks!

I am not super familiar with recommendation systems research in general, but I imagine it would be tricky to convert recommendation sequences into a pure supervised problem like the ones in our paper. It would be possible to use spacetimeformer as a general purpose encoder for sequences in a decision making problem though. You could generate a spatiotemporal representation of your sequence with a spacetimeformer encoder that looks at past timesteps and a decoder with a target sequence that is 1 token long (the current timestep). If you customized the `out_dim >> 2`, the output could then be an input to another system (shape `(batch_size, 1, out_dim)`)
https://github.com/QData/spacetimeformer/blob/2c02b4bad86fa483d96f9ae978bf2bb8467af24e/spacetimeformer/spacetimeformer_model/nn/model.py#L163-L165
