### ISSUE TITLE
How to input npz format data to model training？

### ISSUE THREAD

**Issue by 1347919709** [QData/spacetimeformer#48]
Hello ,dear author,Thank you very much for providing this spacetimeformer model.
But my dataset is a meteorological dataset in npz format, how to input npz into the model?
Which code do I need to see in the repo?

Thank you very much if you would like to help.

**Comment by jakegrigsby** [comment]
Hi, sorry for delayed reply but this will probably take a custom pytorch `Dataset` class for you data. The closest example in the code is probably `data/metr_la.py` which uses a .npz format
