### ISSUE TITLE
How do the results compare to the Autoformer?

### ISSUE THREAD

**Issue by ZetiMente** [QData/spacetimeformer#56]
Hi,

How do the results compare to the Autoformer? https://arxiv.org/abs/2106.13008

It seems the Informer and Autoformer are the front runner models to compare against. But from the paper it seems, the results were compared mostly to older LTSM and GNN style models. Do you have any research in how it compares ?

**Comment by jakegrigsby** [comment]
This will be touched on briefly in the 3rd/last version of the paper. The short answer is it's competitive with Autoformer/ETSFormer/FEDFormer etc., but a lot of the benchmarks those papers use are a lot more about robustness to distribution shift than modeling power (https://arxiv.org/abs/2205.13504)

**Comment by ZetiMente** [comment]
Very interesting, look forward to the 3rd version of the paper with the comparisons to Autoformer.
