### ISSUE TITLE
Request to Submit PR for Issues

### ISSUE THREAD

**Issue by dancassin** [QData/spacetimeformer#69]
Followed the instructions provided on the README, and I have some potential changes if agreed upon:

1. 
`source activate spacetimeformer`
should be:
`conda activate spacetimeformer`

2. 
in order to run the training commands, it requires a second
`cd spacetimeformer`
after lines to install requirements.txt in order to run the train.py

3.
Additon of `torchvision` and `opt_einsum` to requirements.txt

**Comment by jakegrigsby** [comment]
I appreciate the notes, I put some of these changes into the PR that updated the readme for v3 of the arXiv paper. 

Pytorch/torchvision are such key dependencies that the package assumes researchers already have them installed and does not try to install them for you. I do this to avoid dealing with CUDA version control errors that are gpu-specific.
